### ISSUE TITLE
the app is not showing properties and transactions

### ISSUE THREAD

**Issue by sachin2323** [vijaywargiya/ipmanagement-blockchain#2]
the app is working, the transactions are happening its showing on notifications but not showing in the my_transactions tab. The property is also being added, but again its not showing in the My_property tab.
Also, I am unable to see any other transaction happening in the chain. Please also put a description in the home tab, on how to use the app its bit confusing for beginners

**Comment by vijaywargiya** [comment]
Hi Sachin,
How the app works is when you add a property it gets added to the current transaction block. You have to mine the block so that the contents of the block gets finalised. 

Hit /mine url to do so. Your property should then be visible under my propertied.

Thanks
